development:
  adapter: mysql
  encoding: utf8
  database: hitcher_development
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql
  database: hitcher_test
  encoding: utf8
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: hitcher_production
  encoding: utf8
  username: root
  password: 
  host: localhost

cucumber:
  <<: *TEST
