development:
  adapter: mysql
  database: hitcher_development
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql
  database: hitcher_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: hitcher_production
  username: root
  password: 
  host: localhost

cucumber:
  <<: *TEST
