development:
  adapter: sqlite3
  encoding: utf8
  pool: 5 
  timeout: 5000
  database: db/development.sqlite3

test: &TEST
  adapter: sqlite3
  encoding: utf8
  pool: 5 
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: mysql2
  database: hitcher_production
  encoding: utf8
  username: root
  password: 
  host: localhost

cucumber:
  <<: *TEST
